name: Android CI
on:
  pull_request: { branches: [ main, dev ] }
  push: { branches: [ dev ] }
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'
      - name: Build & test
        working-directory: android-app
        run: ./gradlew clean lintDebug testDebugUnitTest assembleDebug --stacktrace
      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android-app/app/build/outputs/apk/debug/*.apk
